spring:
  application:
    name: SmartEd_BackEnd
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    defer-datasource-initialization: ${DEFER_DATASOURCE_INITIALIZATION:true}
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        use_sql_comments: false
        default_batch_fetch_size: 100

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SUPPORT_EMAIL}
    password: ${APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com
            protocols: TLSv1.2 TLSv1.3
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

app:
  jwt:
    secret: ${JWT_SECRET_KEY}
    expiration-ms: ${JWT_EXPIRATION_MS:86400000} # 24h
  auth:
    verification-url: ${VERIFICATION_URL:http://localhost:5173/auth/login}
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:https://smart-ed-front-end.vercel.app,http://localhost:5173,http://127.0.0.1:5173}
  mail:
    brevo-key: ${BREVO_API_KEY:}
    brevo-sender-name: ${BREVO_SENDER_NAME:SmartEd Support Team}

vnpay:
  tmn-code: ${VNPAY_TMN_CODE:3KG2WQQV}
  hash-secret: ${VNPAY_HASH_SECRET:RPAAX90YQ37VN4YFL73Z8B2NY2DXT39C}
  api-url: ${VNPAY_API_URL:https://sandbox.vnpayment.vn/paymentv2/vpcpay.html}
  return-url: ${VNPAY_RETURN_URL:https://smart-ed-front-end.vercel.app/vnpay-return}
  version: ${VNPAY_VERSION:2.1.0}
  command: ${VNPAY_COMMAND:pay}
  order-type: ${VNPAY_ORDER_TYPE:other}
